### ISSUE TITLE
bugfix(slider): 侧栏mask无法关闭 

### ISSUE THREAD

**Issue by zhoulujun** [TencentBlueKing/bkui-vue3#830]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/4243366/222731311-0db8ea6a-4633-4230-958f-35567784ef35.png">

**Comment by zhoulujun** [comment]
index.esm.js:14 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at filterFn (index.esm.js:14:4147)
    at index.esm.js:14:4298
    at Array.findIndex (<anonymous>)
    at BKPopIndexManager.getActiveClickFnIndex (index.esm.js:14:4259)
    at BKPopIndexManager.getActiveClickFn (index.esm.js:14:4359)
    at BKPopIndexManager.onMaskClickFn (index.esm.js:14:6438)
    at HTMLDivElement.<anonymous> (index.esm.js:14:3481)
filterFn @ index.esm.js:14
(anonymous) @ index.esm.js:14
BKPopIndexManager.getActiveClickFnIndex @ index.esm.js:14
BKPopIndexManager.getActiveClickFn @ index.esm.js:14
onMaskClickFn @ index.esm.js:14
(anonymous) @ index.esm.js:14
